"""Add Department

Revision ID: 02230f0c610f
Revises: 455b1aef5bb4
Create Date: 2025-06-17 03:06:57.736272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02230f0c610f'
down_revision = '455b1aef5bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
