"""rename department

Revision ID: 215485279be3
Revises: 02230f0c610f
Create Date: 2025-06-17 03:26:16.639939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215485279be3'
down_revision = '02230f0c610f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
    # ### end Alembic commands ###
